version: '3.4'

services:
  globoticket.services.discount:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings_DefaultConnection=Data Source=db;Initial Catalog=GloboTicketDiscountDb;Integrated Security=False;User ID=sa;Password=password123!

    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    expose:
     - "1433"
    environment:
     SA_PASSWORD: "password123!"
     ACCEPT_EULA: "Y"